
version: '3.1'
services:
  api-pozos:
    container_name: pozos
    image: student-pozos:1
    restart: always
     ports:
      - 8500:5000
    volumes:
      - /simple_api/student_age.json:/data/student_age.json
    networks:
      - studentlist      

  ihm_api:
    container_name: ihm_api
    image: php:apache
    restart: always
    depends_on:
      - api-pozos
    environment:
      USERNAME: "toto"
      PASSWORD: "python"
    volumes:
      - ./website:/var/www/html
    ports:
      - 8080:80
    networks:
      - studentlist
networks:
  studentlist:
